version: '3.10'


services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart : always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
  dev-test :
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory2

name: fastapi-tdd



