version: '3.10'


services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart : always
    ports:
      - "5433:5432"
    env_file:
      - env/.env.dev
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d


#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: inventory
  dev-test :
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - env/.env.test
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: inventory2
  admier :
    image: adminer
    restart: always
    ports:
      - "8080:8080"

name: fastapi-tdd



